baseURL = 'http://blog.manugarg.com/'
languageCode = 'en-us'
title = "Manu's Blog"
theme = 'diary'
googleAnalytics = "G-WJGGB5EHFQ"

[markup.goldmark.renderer]
unsafe = true

[params]
googleSearchCode = '83a141e3fe4224f63'
enableGiscus = true

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "perldoc"
    tabWidth = 4

# Generated at https://giscus.app/
[params.giscus]
  data_repo="manugarg/blog"
  data_repo_id="R_kgDOMIFpRw"    
  data_category="General"
  data_category_id="DIC_kwDOMIFpR84CgCDt"
  data_mapping="title"
  data_strict="0"
  data_reactions_enabled="1"
  data_emit_metadata="0"
  data_input_position="bottom"
  data_theme="preferred_color_scheme"
  data_lang="en"
  crossorigin="anonymous"

[[menu.main]]
url = "/categories"
name = "Categories"
weight = 1
[[menu.main]]
url = "/tags"
name = "Tags"
weight = 2
[[menu.main]]
url = "/posts"
name = "Archive"
weight = 3
